
import { VaseModel, VaseType, Employee, Sector } from './types';
import { v4 as uuidv4 } from 'uuid';

export const DEFAULT_SUPERVISOR_PASS = '1234';

export const INITIAL_EMPLOYEES: Employee[] = [
  { id: '1', name: 'João Silva', sector: Sector.PRODUCTION, role: 'colaborador', active: true },
  { id: '2', name: 'Maria Santos', sector: Sector.FINISHING, role: 'colaborador', active: true },
  { id: '3', name: 'Carlos Oliveira', sector: Sector.PAINTING, role: 'colaborador', active: true },
  { id: '4', name: 'Ana Costa', sector: Sector.SUPERVISOR, role: 'supervisor', active: true },
  { id: '5', name: 'Pedro Souza', sector: Sector.PRODUCTION, role: 'colaborador', active: true },
  { id: '6', name: 'Fernanda Lima', sector: Sector.FINISHING, role: 'colaborador', active: true },
];

export const INITIAL_VASES: VaseModel[] = [
  // --- COM CASCA ---
  { id: uuidv4(), name: 'California P', type: VaseType.WITH_SHELL, weightKg: 8, costProduction: 8.00, costFinishing: 7.20, priceSale: 200.00 },
  { id: uuidv4(), name: 'California M', type: VaseType.WITH_SHELL, weightKg: 14, costProduction: 10.00, costFinishing: 9.00, priceSale: 250.00 },
  { id: uuidv4(), name: 'Bacia Lisa', type: VaseType.WITH_SHELL, weightKg: 14, costProduction: 12.00, costFinishing: 10.80, priceSale: 300.00 },
  { id: uuidv4(), name: 'Jarro', type: VaseType.WITH_SHELL, weightKg: 14, costProduction: 12.00, costFinishing: 10.80, priceSale: 300.00 },
  { id: uuidv4(), name: 'California G', type: VaseType.WITH_SHELL, weightKg: 22, costProduction: 12.00, costFinishing: 10.80, priceSale: 300.00 },
  { id: uuidv4(), name: 'Jambo', type: VaseType.WITH_SHELL, weightKg: 14, costProduction: 12.00, costFinishing: 10.80, priceSale: 300.00 },
  { id: uuidv4(), name: 'Manoel M', type: VaseType.WITH_SHELL, weightKg: 14, costProduction: 12.00, costFinishing: 10.80, priceSale: 300.00 },
  { id: uuidv4(), name: 'Mini Pot', type: VaseType.WITH_SHELL, weightKg: 8, costProduction: 12.00, costFinishing: 10.80, priceSale: 300.00 },
  { id: uuidv4(), name: 'Slim M', type: VaseType.WITH_SHELL, weightKg: 14, costProduction: 15.00, costFinishing: 13.50, priceSale: 375.00 },
  { id: uuidv4(), name: 'California GG', type: VaseType.WITH_SHELL, weightKg: 32, costProduction: 15.00, costFinishing: 13.50, priceSale: 375.00 },
  { id: uuidv4(), name: 'Home P', type: VaseType.WITH_SHELL, weightKg: 8, costProduction: 15.00, costFinishing: 13.50, priceSale: 375.00 },
  { id: uuidv4(), name: 'Mônaco M', type: VaseType.WITH_SHELL, weightKg: 14, costProduction: 15.00, costFinishing: 13.50, priceSale: 375.00 },
  { id: uuidv4(), name: 'Vity', type: VaseType.WITH_SHELL, weightKg: 14, costProduction: 16.00, costFinishing: 14.40, priceSale: 400.00 },
  { id: uuidv4(), name: 'Dubai', type: VaseType.WITH_SHELL, weightKg: 14, costProduction: 16.00, costFinishing: 14.40, priceSale: 400.00 },
  { id: uuidv4(), name: 'Cilindro', type: VaseType.WITH_SHELL, weightKg: 14, costProduction: 16.00, costFinishing: 14.40, priceSale: 400.00 },
  { id: uuidv4(), name: 'Paris', type: VaseType.WITH_SHELL, weightKg: 22, costProduction: 16.00, costFinishing: 14.40, priceSale: 400.00 },
  { id: uuidv4(), name: 'Bola M', type: VaseType.WITH_SHELL, weightKg: 14, costProduction: 18.00, costFinishing: 16.20, priceSale: 500.00 },
  { id: uuidv4(), name: 'Home G', type: VaseType.WITH_SHELL, weightKg: 22, costProduction: 18.00, costFinishing: 16.20, priceSale: 500.00 },
  { id: uuidv4(), name: 'Bali', type: VaseType.WITH_SHELL, weightKg: 14, costProduction: 18.00, costFinishing: 16.20, priceSale: 500.00 },
  { id: uuidv4(), name: 'Mônaco G', type: VaseType.WITH_SHELL, weightKg: 22, costProduction: 18.00, costFinishing: 16.20, priceSale: 500.00 },
  { id: uuidv4(), name: 'Áustria', type: VaseType.WITH_SHELL, weightKg: 14, costProduction: 18.00, costFinishing: 16.20, priceSale: 500.00 },
  { id: uuidv4(), name: 'Slim G', type: VaseType.WITH_SHELL, weightKg: 22, costProduction: 20.00, costFinishing: 18.00, priceSale: 600.00 },
  { id: uuidv4(), name: 'Roma', type: VaseType.WITH_SHELL, weightKg: 14, costProduction: 20.00, costFinishing: 18.00, priceSale: 600.00 },
  { id: uuidv4(), name: 'Georgia', type: VaseType.WITH_SHELL, weightKg: 14, costProduction: 20.00, costFinishing: 18.00, priceSale: 600.00 },
  { id: uuidv4(), name: 'Moscou', type: VaseType.WITH_SHELL, weightKg: 14, costProduction: 20.00, costFinishing: 18.00, priceSale: 600.00 },
  { id: uuidv4(), name: 'Portugal', type: VaseType.WITH_SHELL, weightKg: 14, costProduction: 20.00, costFinishing: 18.00, priceSale: 600.00 },
  { id: uuidv4(), name: 'Heitor', type: VaseType.WITH_SHELL, weightKg: 22, costProduction: 25.00, costFinishing: 22.50, priceSale: 800.00 },
  { id: uuidv4(), name: 'Veneza', type: VaseType.WITH_SHELL, weightKg: 22, costProduction: 25.00, costFinishing: 22.50, priceSale: 800.00 },
  { id: uuidv4(), name: 'Granada', type: VaseType.WITH_SHELL, weightKg: 22, costProduction: 25.00, costFinishing: 22.50, priceSale: 800.00 },
  { id: uuidv4(), name: 'Apogeu', type: VaseType.WITH_SHELL, weightKg: 22, costProduction: 25.00, costFinishing: 22.50, priceSale: 800.00 },
  { id: uuidv4(), name: 'Ânfora 90cm', type: VaseType.WITH_SHELL, weightKg: 32, costProduction: 30.00, costFinishing: 27.00, priceSale: 1000.00 },
  { id: uuidv4(), name: 'Irã', type: VaseType.WITH_SHELL, weightKg: 22, costProduction: 35.00, costFinishing: 31.50, priceSale: 1000.00 },
  { id: uuidv4(), name: 'Madri', type: VaseType.WITH_SHELL, weightKg: 22, costProduction: 35.00, costFinishing: 31.50, priceSale: 1000.00 },
  { id: uuidv4(), name: 'Ânfora', type: VaseType.WITH_SHELL, weightKg: 32, costProduction: 50.00, costFinishing: 45.00, priceSale: 1250.00 },

  // --- SEM CASCA ---
  { id: uuidv4(), name: 'Vity', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 8.00 },
  { id: uuidv4(), name: 'Dubai', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 8.00 },
  { id: uuidv4(), name: 'Bola M', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 10.00 },
  { id: uuidv4(), name: 'Cilindro', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 8.00 },
  { id: uuidv4(), name: 'Paris', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 8.00 },
  { id: uuidv4(), name: 'Slim G', type: VaseType.WITHOUT_SHELL, weightKg: 22, costProduction: 10.00 },
  { id: uuidv4(), name: 'Slim M', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 8.00 },
  { id: uuidv4(), name: 'Bacia Lisa', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 6.00 },
  { id: uuidv4(), name: 'Irã', type: VaseType.WITHOUT_SHELL, weightKg: 22, costProduction: 20.00 },
  { id: uuidv4(), name: 'Madri', type: VaseType.WITHOUT_SHELL, weightKg: 22, costProduction: 15.00 },
  { id: uuidv4(), name: 'Ânfora', type: VaseType.WITHOUT_SHELL, weightKg: 32, costProduction: 40.00 },
  { id: uuidv4(), name: 'Jarro', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 5.00 },
  { id: uuidv4(), name: 'California GG', type: VaseType.WITHOUT_SHELL, weightKg: 32, costProduction: 7.00 },
  { id: uuidv4(), name: 'California G', type: VaseType.WITHOUT_SHELL, weightKg: 22, costProduction: 6.00 },
  { id: uuidv4(), name: 'California M', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 5.00 },
  { id: uuidv4(), name: 'California P', type: VaseType.WITHOUT_SHELL, weightKg: 8, costProduction: 4.00 },
  { id: uuidv4(), name: 'Jambo', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 5.00 },
  { id: uuidv4(), name: 'Home G', type: VaseType.WITHOUT_SHELL, weightKg: 22, costProduction: 10.00 },
  { id: uuidv4(), name: 'Home P', type: VaseType.WITHOUT_SHELL, weightKg: 8, costProduction: 8.00 },
  { id: uuidv4(), name: 'Manoel M', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 5.00 },
  { id: uuidv4(), name: 'Roma', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 6.00 },
  { id: uuidv4(), name: 'Rubi', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 8.00 },
  { id: uuidv4(), name: 'Colmeia G', type: VaseType.WITHOUT_SHELL, weightKg: 22, costProduction: 6.00 },
  { id: uuidv4(), name: 'Colmeia M', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 4.00 },
  { id: uuidv4(), name: 'Bacia Diamante', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 4.00 },
  { id: uuidv4(), name: 'Jardineira', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 8.00 },
  { id: uuidv4(), name: 'Romano', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 12.00 },
  { id: uuidv4(), name: 'Veneza', type: VaseType.WITHOUT_SHELL, weightKg: 22, costProduction: 15.00 },
  { id: uuidv4(), name: 'Bali', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 8.00 },
  { id: uuidv4(), name: 'Georgia', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 8.00 },
  { id: uuidv4(), name: 'Veneza s/ borda', type: VaseType.WITHOUT_SHELL, weightKg: 22, costProduction: 13.00 },
  { id: uuidv4(), name: 'Bacia Lisa P', type: VaseType.WITHOUT_SHELL, weightKg: 8, costProduction: 4.00 },
  { id: uuidv4(), name: 'Bacia Vity', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 5.00 },
  { id: uuidv4(), name: 'Moscou', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 10.00 },
  { id: uuidv4(), name: 'Pipoos G', type: VaseType.WITHOUT_SHELL, weightKg: 22, costProduction: 5.00 },
  { id: uuidv4(), name: 'Diamante G', type: VaseType.WITHOUT_SHELL, weightKg: 22, costProduction: 6.00 },
  { id: uuidv4(), name: 'Granada', type: VaseType.WITHOUT_SHELL, weightKg: 22, costProduction: 15.00 },
  { id: uuidv4(), name: 'Mônaco G', type: VaseType.WITHOUT_SHELL, weightKg: 22, costProduction: 8.00 },
  { id: uuidv4(), name: 'Mônaco M', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 8.00 },
  { id: uuidv4(), name: 'Lótus', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 5.00 },
  { id: uuidv4(), name: 'Ânfora 90cm', type: VaseType.WITHOUT_SHELL, weightKg: 32, costProduction: 20.00 },
  { id: uuidv4(), name: 'Portugal', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 15.00 },
  { id: uuidv4(), name: 'Áustria', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 10.00 },
  { id: uuidv4(), name: 'Apogeu / Atlantis', type: VaseType.WITHOUT_SHELL, weightKg: 22, costProduction: 15.00 },
  { id: uuidv4(), name: 'Zezo', type: VaseType.WITHOUT_SHELL, weightKg: 8, costProduction: 4.00 },
  { id: uuidv4(), name: 'Helena', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 16.00 },
  { id: uuidv4(), name: 'Heitor', type: VaseType.WITHOUT_SHELL, weightKg: 22, costProduction: 10.00 },
  { id: uuidv4(), name: 'Vitória G', type: VaseType.WITHOUT_SHELL, weightKg: 22, costProduction: 6.00 },
  { id: uuidv4(), name: 'Vitória M', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 5.00 },
  { id: uuidv4(), name: 'Coluna Des. G', type: VaseType.WITHOUT_SHELL, weightKg: 22, costProduction: 10.00 },
  { id: uuidv4(), name: 'Coluna Des. P', type: VaseType.WITHOUT_SHELL, weightKg: 8, costProduction: 5.00 },
  { id: uuidv4(), name: 'Tacho', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 5.00 },
  { id: uuidv4(), name: 'Mexicana', type: VaseType.WITHOUT_SHELL, weightKg: 14, costProduction: 5.00 },
];
